FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

# Argumentos y variables de entorno para React
ARG REACT_APP_ACCESS_KEY_ID
ARG REACT_APP_SECRET_ACCESS_KEY
ARG REACT_APP_AWS_REGION
ARG REACT_APP_AGENT_ID
ARG REACT_APP_AGENT_ALIAS_ID
ARG REACT_APP_QUESTION_ANSWERS_TABLE_NAME
ARG REACT_APP_MODEL_ID_FOR_CHART

ENV REACT_APP_ACCESS_KEY_ID=$REACT_APP_ACCESS_KEY_ID
ENV REACT_APP_SECRET_ACCESS_KEY=$REACT_APP_SECRET_ACCESS_KEY
ENV REACT_APP_AWS_REGION=$REACT_APP_AWS_REGION
ENV REACT_APP_AGENT_ID=$REACT_APP_AGENT_ID
ENV REACT_APP_AGENT_ALIAS_ID=$REACT_APP_AGENT_ALIAS_ID
ENV REACT_APP_QUESTION_ANSWERS_TABLE_NAME=$REACT_APP_QUESTION_ANSWERS_TABLE_NAME
ENV REACT_APP_MODEL_ID_FOR_CHART=$REACT_APP_MODEL_ID_FOR_CHART

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
